name: Auto Presensi

on:
  schedule:
    - cron: '0 0 * * 1-5'   # Jam 07:00 WIB (00:00 UTC), Senin - Jumat
    - cron: '0 9 * * 1-5'   # Jam 16:00 WIB (09:00 UTC), Senin - Jumat
  workflow_dispatch:        # Bisa dijalankan manual lewat tombol "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python main.py
